using NextGen.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NextGen.Domain.Abstract
{
    public interface IDbContext : IDisposable
    {
        DbSet<ad_ca_abs_lending_purpose_code> ad_ca_abs_lending_purpose_code { get; set; }
        DbSet<ad_ca_abs_occupation_code> ad_ca_abs_occupation_code { get; set; }
        DbSet<ad_ca_address_type> ad_ca_address_type { get; set; }
        DbSet<ad_ca_agricultural_asset_type> ad_ca_agricultural_asset_type { get; set; }
        DbSet<ad_ca_aircraft_type> ad_ca_aircraft_type { get; set; }
        DbSet<ad_ca_annotation_type> ad_ca_annotation_type { get; set; }
        DbSet<ad_ca_anzsic_industry_code> ad_ca_anzsic_industry_code { get; set; }
        DbSet<ad_ca_applicant_type> ad_ca_applicant_type { get; set; }
        DbSet<ad_ca_application_doc_type> ad_ca_application_doc_type { get; set; }
        DbSet<ad_ca_application_type> ad_ca_application_type { get; set; }
        DbSet<ad_ca_assessment_type_application_instructions_type> ad_ca_assessment_type_application_instructions_type { get; set; }
        DbSet<ad_ca_asset_transaction_type> ad_ca_asset_transaction_type { get; set; }
        DbSet<ad_ca_au_dialing_code> ad_ca_au_dialing_code { get; set; }
        DbSet<ad_ca_au_state_type> ad_ca_au_state_type { get; set; }
        DbSet<ad_ca_balloon_rv_input_pattern_type> ad_ca_balloon_rv_input_pattern_type { get; set; }
        DbSet<ad_ca_builder_type> ad_ca_builder_type { get; set; }
        DbSet<ad_ca_business_channel_type> ad_ca_business_channel_type { get; set; }
        DbSet<ad_ca_business_structure_excluding_trust_type> ad_ca_business_structure_excluding_trust_type { get; set; }
        DbSet<ad_ca_business_structure_full_type> ad_ca_business_structure_full_type { get; set; }
        DbSet<ad_ca_cleaning_equipment_type> ad_ca_cleaning_equipment_type { get; set; }
        DbSet<ad_ca_clearing_from_other_source_type> ad_ca_clearing_from_other_source_type { get; set; }
        DbSet<ad_ca_clearing_from_this_loan_type> ad_ca_clearing_from_this_loan_type { get; set; }
        DbSet<ad_ca_collateral_type> ad_ca_collateral_type { get; set; }
        DbSet<ad_ca_commercial_type> ad_ca_commercial_type { get; set; }
        DbSet<ad_ca_commission_structure_type> ad_ca_commission_structure_type { get; set; }
        DbSet<ad_ca_condition_owner_application_instructions_type> ad_ca_condition_owner_application_instructions_type { get; set; }
        DbSet<ad_ca_condition_status_application_instructions_type> ad_ca_condition_status_application_instructions_type { get; set; }
        DbSet<ad_ca_condition_type> ad_ca_condition_type { get; set; }
        DbSet<ad_ca_construction_type> ad_ca_construction_type { get; set; }
        DbSet<ad_ca_contact_email_type> ad_ca_contact_email_type { get; set; }
        DbSet<ad_ca_contribution_funds_type> ad_ca_contribution_funds_type { get; set; }
        DbSet<ad_ca_country_code> ad_ca_country_code { get; set; }
        DbSet<ad_ca_credit_card_type> ad_ca_credit_card_type { get; set; }
        DbSet<ad_ca_credit_history_issue_type> ad_ca_credit_history_issue_type { get; set; }
        DbSet<ad_ca_credit_reporting_body_type> ad_ca_credit_reporting_body_type { get; set; }
        DbSet<ad_ca_credit_status_type> ad_ca_credit_status_type { get; set; }
        DbSet<ad_ca_currency_code> ad_ca_currency_code { get; set; }
        DbSet<ad_ca_data_source_type> ad_ca_data_source_type { get; set; }
        DbSet<ad_ca_declined_reason_application_instructions_type> ad_ca_declined_reason_application_instructions_type { get; set; }
        DbSet<ad_ca_document_category_type> ad_ca_document_category_type { get; set; }
        DbSet<ad_ca_document_type> ad_ca_document_type { get; set; }
        DbSet<ad_ca_documentation_instructions_method_type> ad_ca_documentation_instructions_method_type { get; set; }
        DbSet<ad_ca_duration_units_type> ad_ca_duration_units_type { get; set; }
        DbSet<ad_ca_earth_moving_mining_and_construction_type> ad_ca_earth_moving_mining_and_construction_type { get; set; }
        DbSet<ad_ca_employer_type> ad_ca_employer_type { get; set; }
        DbSet<ad_ca_employment_status_type> ad_ca_employment_status_type { get; set; }
        DbSet<ad_ca_error_instructions_type> ad_ca_error_instructions_type { get; set; }
        DbSet<ad_ca_error_source_type> ad_ca_error_source_type { get; set; }
        DbSet<ad_ca_estimate_basis_non_real_estate_asset_type> ad_ca_estimate_basis_non_real_estate_asset_type { get; set; }
        DbSet<ad_ca_estimate_basis_real_estate_asset_type> ad_ca_estimate_basis_real_estate_asset_type { get; set; }
        DbSet<ad_ca_event_name_application_instructions_type> ad_ca_event_name_application_instructions_type { get; set; }
        DbSet<ad_ca_exempt_status_type> ad_ca_exempt_status_type { get; set; }
        DbSet<ad_ca_fee_category_type> ad_ca_fee_category_type { get; set; }
        DbSet<ad_ca_fee_type> ad_ca_fee_type { get; set; }
        DbSet<ad_ca_financial_asset_type> ad_ca_financial_asset_type { get; set; }
        DbSet<ad_ca_financial_institution_type> ad_ca_financial_institution_type { get; set; }
        DbSet<ad_ca_financial_transaction_type> ad_ca_financial_transaction_type { get; set; }
        DbSet<ad_ca_frequency_full_type> ad_ca_frequency_full_type { get; set; }
        DbSet<ad_ca_frequency_short_type> ad_ca_frequency_short_type { get; set; }
        DbSet<ad_ca_funder_type> ad_ca_funder_type { get; set; }
        DbSet<ad_ca_gender_type> ad_ca_gender_type { get; set; }
        DbSet<ad_ca_good_to_be_used_location_type> ad_ca_good_to_be_used_location_type { get; set; }
        DbSet<ad_ca_goods_delivery_type> ad_ca_goods_delivery_type { get; set; }
        DbSet<ad_ca_government_benefits_type> ad_ca_government_benefits_type { get; set; }
        DbSet<ad_ca_guarantor_access_type> ad_ca_guarantor_access_type { get; set; }
        DbSet<ad_ca_holding_type> ad_ca_holding_type { get; set; }
        DbSet<ad_ca_hospitality_and_leisure_type> ad_ca_hospitality_and_leisure_type { get; set; }
        DbSet<ad_ca_housing_status_type> ad_ca_housing_status_type { get; set; }
        DbSet<ad_ca_income_verification_type> ad_ca_income_verification_type { get; set; }
        DbSet<ad_ca_industrial_type> ad_ca_industrial_type { get; set; }
        DbSet<ad_ca_instalments_frequency_type> ad_ca_instalments_frequency_type { get; set; }
        DbSet<ad_ca_insurance_type> ad_ca_insurance_type { get; set; }
        DbSet<ad_ca_insurer_type> ad_ca_insurer_type { get; set; }
        DbSet<ad_ca_interest_type> ad_ca_interest_type { get; set; }
        DbSet<ad_ca_it_and_av_equipment_type> ad_ca_it_and_av_equipment_type { get; set; }
        DbSet<ad_ca_kin_relationship_type> ad_ca_kin_relationship_type { get; set; }
        DbSet<ad_ca_land_area_units_type> ad_ca_land_area_units_type { get; set; }
        DbSet<ad_ca_land_value_estimate_basis_type> ad_ca_land_value_estimate_basis_type { get; set; }
        DbSet<ad_ca_lending_guarantee_type> ad_ca_lending_guarantee_type { get; set; }
        DbSet<ad_ca_liability_type> ad_ca_liability_type { get; set; }
        DbSet<ad_ca_licence_type> ad_ca_licence_type { get; set; }
        DbSet<ad_ca_living_expense_category_type> ad_ca_living_expense_category_type { get; set; }
        DbSet<ad_ca_loan_term_units_type> ad_ca_loan_term_units_type { get; set; }
        DbSet<ad_ca_loan_type> ad_ca_loan_type { get; set; }
        DbSet<ad_ca_marital_status_type> ad_ca_marital_status_type { get; set; }
        DbSet<ad_ca_master_agreement_status_type> ad_ca_master_agreement_status_type { get; set; }
        DbSet<ad_ca_materials_handling_and_lifting_type> ad_ca_materials_handling_and_lifting_type { get; set; }
        DbSet<ad_ca_medical_equipment_type> ad_ca_medical_equipment_type { get; set; }
        DbSet<ad_ca_mitigant_factor_type> ad_ca_mitigant_factor_type { get; set; }
        DbSet<ad_ca_mm_month_type> ad_ca_mm_month_type { get; set; }
        DbSet<ad_ca_mobile_computing_type> ad_ca_mobile_computing_type { get; set; }
        DbSet<ad_ca_name_title_type> ad_ca_name_title_type { get; set; }
        DbSet<ad_ca_nccp_status_type> ad_ca_nccp_status_type { get; set; }
        DbSet<ad_ca_non_real_estate_asset_type> ad_ca_non_real_estate_asset_type { get; set; }
        DbSet<ad_ca_nras_consortium_type> ad_ca_nras_consortium_type { get; set; }
        DbSet<ad_ca_occupancy_type> ad_ca_occupancy_type { get; set; }
        DbSet<ad_ca_office_equipment_type> ad_ca_office_equipment_type { get; set; }
        DbSet<ad_ca_other_asset_type> ad_ca_other_asset_type { get; set; }
        DbSet<ad_ca_other_commitment_category_type> ad_ca_other_commitment_category_type { get; set; }
        DbSet<ad_ca_other_income_type> ad_ca_other_income_type { get; set; }
        DbSet<ad_ca_partner_type> ad_ca_partner_type { get; set; }
        DbSet<ad_ca_pay_fees_from_type> ad_ca_pay_fees_from_type { get; set; }
        DbSet<ad_ca_payg_basis_type> ad_ca_payg_basis_type { get; set; }
        DbSet<ad_ca_payment_timing_type> ad_ca_payment_timing_type { get; set; }
        DbSet<ad_ca_payment_type> ad_ca_payment_type { get; set; }
        DbSet<ad_ca_plan_type> ad_ca_plan_type { get; set; }
        DbSet<ad_ca_plant_equipment_and_industrial_type> ad_ca_plant_equipment_and_industrial_type { get; set; }
        DbSet<ad_ca_po_box_type> ad_ca_po_box_type { get; set; }
        DbSet<ad_ca_pool_type> ad_ca_pool_type { get; set; }
        DbSet<ad_ca_power_of_attorney_type> ad_ca_power_of_attorney_type { get; set; }
        DbSet<ad_ca_pre_condition_to_stage_application_instructions_type> ad_ca_pre_condition_to_stage_application_instructions_type { get; set; }
        DbSet<ad_ca_preferred_contact_company_type> ad_ca_preferred_contact_company_type { get; set; }
        DbSet<ad_ca_preferred_contact_person_type> ad_ca_preferred_contact_person_type { get; set; }
        DbSet<ad_ca_primary_purpose_loan_purpose_type> ad_ca_primary_purpose_loan_purpose_type { get; set; }
        DbSet<ad_ca_primary_purpose_real_estate_asset_type> ad_ca_primary_purpose_real_estate_asset_type { get; set; }
        DbSet<ad_ca_primary_usage_type> ad_ca_primary_usage_type { get; set; }
        DbSet<ad_ca_principal_refinancing_reason_type> ad_ca_principal_refinancing_reason_type { get; set; }
        DbSet<ad_ca_proof_code_company_type> ad_ca_proof_code_company_type { get; set; }
        DbSet<ad_ca_proof_code_not_employed_type> ad_ca_proof_code_not_employed_type { get; set; }
        DbSet<ad_ca_proof_code_other_type> ad_ca_proof_code_other_type { get; set; }
        DbSet<ad_ca_proof_code_payg_type> ad_ca_proof_code_payg_type { get; set; }
        DbSet<ad_ca_proof_code_self_employed_type> ad_ca_proof_code_self_employed_type { get; set; }
        DbSet<ad_ca_proof_code_trust_type> ad_ca_proof_code_trust_type { get; set; }
        DbSet<ad_ca_proportions_type> ad_ca_proportions_type { get; set; }
        DbSet<ad_ca_proposed_repayment_method_type> ad_ca_proposed_repayment_method_type { get; set; }
        DbSet<ad_ca_real_estate_asset_status_type> ad_ca_real_estate_asset_status_type { get; set; }
        DbSet<ad_ca_registration_state_type> ad_ca_registration_state_type { get; set; }
        DbSet<ad_ca_release_security_reason_type> ad_ca_release_security_reason_type { get; set; }
        DbSet<ad_ca_repayment_frequency_type> ad_ca_repayment_frequency_type { get; set; }
        DbSet<ad_ca_residency_status_type> ad_ca_residency_status_type { get; set; }
        DbSet<ad_ca_residential_type> ad_ca_residential_type { get; set; }
        DbSet<ad_ca_rural_type> ad_ca_rural_type { get; set; }
        DbSet<ad_ca_rural_usage_type> ad_ca_rural_usage_type { get; set; }
        DbSet<ad_ca_security_priority_type> ad_ca_security_priority_type { get; set; }
        DbSet<ad_ca_self_employed_basis_type> ad_ca_self_employed_basis_type { get; set; }
        DbSet<ad_ca_send_documents_to_person_type> ad_ca_send_documents_to_person_type { get; set; }
        DbSet<ad_ca_send_documents_to_type> ad_ca_send_documents_to_type { get; set; }
        DbSet<ad_ca_share_type> ad_ca_share_type { get; set; }
        DbSet<ad_ca_significant_change_type> ad_ca_significant_change_type { get; set; }
        DbSet<ad_ca_statement_cycle_type> ad_ca_statement_cycle_type { get; set; }
        DbSet<ad_ca_status_name_application_instructions_type> ad_ca_status_name_application_instructions_type { get; set; }
        DbSet<ad_ca_street_suffix_type> ad_ca_street_suffix_type { get; set; }
        DbSet<ad_ca_street_type> ad_ca_street_type { get; set; }
        DbSet<ad_ca_supplier_type> ad_ca_supplier_type { get; set; }
        DbSet<ad_ca_surplus_funds_disbursement_method_type> ad_ca_surplus_funds_disbursement_method_type { get; set; }
        DbSet<ad_ca_tax_depreciation_method_type> ad_ca_tax_depreciation_method_type { get; set; }
        DbSet<ad_ca_tenure_type> ad_ca_tenure_type { get; set; }
        DbSet<ad_ca_title_system_type> ad_ca_title_system_type { get; set; }
        DbSet<ad_ca_tools_of_trade_type> ad_ca_tools_of_trade_type { get; set; }
        DbSet<ad_ca_total_term_type> ad_ca_total_term_type { get; set; }
        DbSet<ad_ca_trust_purpose_type> ad_ca_trust_purpose_type { get; set; }
        DbSet<ad_ca_trust_structure_type> ad_ca_trust_structure_type { get; set; }
        DbSet<ad_ca_type_of_incorporation_type> ad_ca_type_of_incorporation_type { get; set; }
        DbSet<ad_ca_valuation_program_type> ad_ca_valuation_program_type { get; set; }
        DbSet<ad_ca_variation_type> ad_ca_variation_type { get; set; }
        DbSet<ad_ca_vary_on_valuation_type> ad_ca_vary_on_valuation_type { get; set; }
        DbSet<ad_ca_vehicle_type> ad_ca_vehicle_type { get; set; }
        DbSet<ad_ca_visit_contact_type> ad_ca_visit_contact_type { get; set; }
        DbSet<ad_ca_yy_year_type> ad_ca_yy_year_type { get; set; }
        DbSet<ad_ch_submission_type> ad_ch_submission_type { get; set; }
        DbSet<ad_ed_account_type> ad_ed_account_type { get; set; }
        DbSet<ad_ed_application_accuracy_error_type> ad_ed_application_accuracy_error_type { get; set; }
        DbSet<ad_ed_application_cancel_reason_type> ad_ed_application_cancel_reason_type { get; set; }
        DbSet<ad_ed_case_status_type> ad_ed_case_status_type { get; set; }
        DbSet<ad_ed_credit_application_condition_type> ad_ed_credit_application_condition_type { get; set; }
        DbSet<ad_ed_credit_assessor_dla_type> ad_ed_credit_assessor_dla_type { get; set; }
        DbSet<ad_ed_credit_document_type> ad_ed_credit_document_type { get; set; }
        DbSet<ad_ed_discretion_reason_type> ad_ed_discretion_reason_type { get; set; }
        DbSet<ad_ed_employment_type> ad_ed_employment_type { get; set; }
        DbSet<ad_ed_institution_branch_type> ad_ed_institution_branch_type { get; set; }
        DbSet<ad_ed_institution_type> ad_ed_institution_type { get; set; }
        DbSet<ad_ed_insurance_classification_type> ad_ed_insurance_classification_type { get; set; }
        DbSet<ad_ed_insurance_cover_type> ad_ed_insurance_cover_type { get; set; }
        DbSet<ad_ed_insurance_how_paid_type> ad_ed_insurance_how_paid_type { get; set; }
        DbSet<ad_ed_lender_purpose_code> ad_ed_lender_purpose_code { get; set; }
        DbSet<ad_ed_member_class_type> ad_ed_member_class_type { get; set; }
        DbSet<ad_ed_member_type> ad_ed_member_type { get; set; }
        DbSet<ad_ed_not_employed_income_type> ad_ed_not_employed_income_type { get; set; }
        DbSet<ad_ed_override_reason_type> ad_ed_override_reason_type { get; set; }
        DbSet<ad_ed_payg_income_type> ad_ed_payg_income_type { get; set; }
        DbSet<ad_ed_property_type_name_type> ad_ed_property_type_name_type { get; set; }
        DbSet<ad_ed_registration_plate_type> ad_ed_registration_plate_type { get; set; }
        DbSet<ad_ed_self_employed_income_type> ad_ed_self_employed_income_type { get; set; }
        DbSet<ad_ed_veda_account_type> ad_ed_veda_account_type { get; set; }
        DbSet<ad_ed_veda_permission_type> ad_ed_veda_permission_type { get; set; }
        DbSet<ad_ed_veda_permission_type_scorecard> ad_ed_veda_permission_type_scorecard { get; set; }
        DbSet<ad_ed_veda_relationship_code> ad_ed_veda_relationship_code { get; set; }
        DbSet<ad_ed_vehicle_body_type> ad_ed_vehicle_body_type { get; set; }
        DbSet<ad_ed_vehicle_make_type> ad_ed_vehicle_make_type { get; set; }
        DbSet<ad_ed_workflow_interface_type> ad_ed_workflow_interface_type { get; set; }
        DbSet<ad_pd_product_type> ad_pd_product_type { get; set; }
        DbSet<ca_address> ca_address { get; set; }
        DbSet<ca_address_dx_box> ca_address_dx_box { get; set; }
        DbSet<ca_address_non_standard> ca_address_non_standard { get; set; }
        DbSet<ca_address_po_box> ca_address_po_box { get; set; }
        DbSet<ca_address_standard> ca_address_standard { get; set; }
        DbSet<ca_affordability> ca_affordability { get; set; }
        DbSet<ca_case_data> ca_case_data { get; set; }
        DbSet<ca_company_applicant> ca_company_applicant { get; set; }
        DbSet<ca_credit_application> ca_credit_application { get; set; }
        DbSet<ca_credit_application_conditions> ca_credit_application_conditions { get; set; }
        DbSet<ca_household> ca_household { get; set; }
        DbSet<ca_household_applicant> ca_household_applicant { get; set; }
        DbSet<ca_household_living_expense> ca_household_living_expense { get; set; }
        DbSet<ca_household_living_expense_percent_responsible_owner> ca_household_living_expense_percent_responsible_owner { get; set; }
        DbSet<ca_household_other_commitment> ca_household_other_commitment { get; set; }
        DbSet<ca_household_other_commitment_percent_responsible_owner> ca_household_other_commitment_percent_responsible_owner { get; set; }
        DbSet<ca_insurance> ca_insurance { get; set; }
        DbSet<ca_insurance_commission_payable> ca_insurance_commission_payable { get; set; }
        DbSet<ca_insurance_premium> ca_insurance_premium { get; set; }
        DbSet<ca_liability> ca_liability { get; set; }
        DbSet<ca_liability_account_number> ca_liability_account_number { get; set; }
        DbSet<ca_liability_account_performance> ca_liability_account_performance { get; set; }
        DbSet<ca_liability_percent_owned_owner> ca_liability_percent_owned_owner { get; set; }
        DbSet<ca_loan_details> ca_loan_details { get; set; }
        DbSet<ca_loan_details_lending_purpose> ca_loan_details_lending_purpose { get; set; }
        DbSet<ca_loan_details_loan_auto_decision> ca_loan_details_loan_auto_decision { get; set; }
        DbSet<ca_loan_details_loan_auto_decision_result> ca_loan_details_loan_auto_decision_result { get; set; }
        DbSet<ca_loan_details_loan_purpose> ca_loan_details_loan_purpose { get; set; }
        DbSet<ca_loan_details_loan_score_card> ca_loan_details_loan_score_card { get; set; }
        DbSet<ca_loan_details_loan_score_card_result> ca_loan_details_loan_score_card_result { get; set; }
        DbSet<ca_loan_details_percent_owned_owner> ca_loan_details_percent_owned_owner { get; set; }
        DbSet<ca_loan_details_proposed_repayment> ca_loan_details_proposed_repayment { get; set; }
        DbSet<ca_loan_details_term> ca_loan_details_term { get; set; }
        DbSet<ca_non_real_estate_asset> ca_non_real_estate_asset { get; set; }
        DbSet<ca_non_real_estate_asset_estimated_value> ca_non_real_estate_asset_estimated_value { get; set; }
        DbSet<ca_non_real_estate_asset_financial_asset> ca_non_real_estate_asset_financial_asset { get; set; }
        DbSet<ca_non_real_estate_asset_financial_asset_account_number> ca_non_real_estate_asset_financial_asset_account_number { get; set; }
        DbSet<ca_non_real_estate_asset_financial_asset_account_performance> ca_non_real_estate_asset_financial_asset_account_performance { get; set; }
        DbSet<ca_non_real_estate_asset_financial_asset_shares> ca_non_real_estate_asset_financial_asset_shares { get; set; }
        DbSet<ca_non_real_estate_asset_insurance> ca_non_real_estate_asset_insurance { get; set; }
        DbSet<ca_non_real_estate_asset_motor_vehicle> ca_non_real_estate_asset_motor_vehicle { get; set; }
        DbSet<ca_non_real_estate_asset_other_asset> ca_non_real_estate_asset_other_asset { get; set; }
        DbSet<ca_non_real_estate_asset_percent_owned_owner> ca_non_real_estate_asset_percent_owned_owner { get; set; }
        DbSet<ca_other_income> ca_other_income { get; set; }
        DbSet<ca_other_income_percent_owned_owner> ca_other_income_percent_owned_owner { get; set; }
        DbSet<ca_person_applicant> ca_person_applicant { get; set; }
        DbSet<ca_person_applicant_affordability> ca_person_applicant_affordability { get; set; }
        DbSet<ca_person_applicant_contact> ca_person_applicant_contact { get; set; }
        DbSet<ca_person_applicant_contact_current_address> ca_person_applicant_contact_current_address { get; set; }
        DbSet<ca_person_applicant_contact_email_address> ca_person_applicant_contact_email_address { get; set; }
        DbSet<ca_person_applicant_contact_home_phone> ca_person_applicant_contact_home_phone { get; set; }
        DbSet<ca_person_applicant_contact_mobile> ca_person_applicant_contact_mobile { get; set; }
        DbSet<ca_person_applicant_contact_previous_address> ca_person_applicant_contact_previous_address { get; set; }
        DbSet<ca_person_applicant_contact_work_phone> ca_person_applicant_contact_work_phone { get; set; }
        DbSet<ca_person_applicant_employment> ca_person_applicant_employment { get; set; }
        DbSet<ca_person_applicant_employment_not_employed> ca_person_applicant_employment_not_employed { get; set; }
        DbSet<ca_person_applicant_employment_payg> ca_person_applicant_employment_payg { get; set; }
        DbSet<ca_person_applicant_employment_self_employed> ca_person_applicant_employment_self_employed { get; set; }
        DbSet<ca_person_applicant_employment_self_employed_business> ca_person_applicant_employment_self_employed_business { get; set; }
        DbSet<ca_person_applicant_employment_self_employed_business_income_recent> ca_person_applicant_employment_self_employed_business_income_recent { get; set; }
        DbSet<ca_person_applicant_proof_of_identity> ca_person_applicant_proof_of_identity { get; set; }
        DbSet<ca_real_estate_asset> ca_real_estate_asset { get; set; }
        DbSet<ca_real_estate_asset_commercial> ca_real_estate_asset_commercial { get; set; }
        DbSet<ca_real_estate_asset_estimated_value> ca_real_estate_asset_estimated_value { get; set; }
        DbSet<ca_real_estate_asset_insurance> ca_real_estate_asset_insurance { get; set; }
        DbSet<ca_real_estate_asset_percent_owned_owner> ca_real_estate_asset_percent_owned_owner { get; set; }
        DbSet<ca_real_estate_asset_rental_income> ca_real_estate_asset_rental_income { get; set; }
        DbSet<ca_real_estate_asset_residential> ca_real_estate_asset_residential { get; set; }
        DbSet<ca_real_estate_asset_rural> ca_real_estate_asset_rural { get; set; }
        DbSet<ca_real_estate_asset_title> ca_real_estate_asset_title { get; set; }
        DbSet<ca_related_company> ca_related_company { get; set; }
        DbSet<ca_related_company_contact> ca_related_company_contact { get; set; }
        DbSet<ca_related_company_contact_contact_person> ca_related_company_contact_contact_person { get; set; }
        DbSet<ca_related_company_contact_office_fax> ca_related_company_contact_office_fax { get; set; }
        DbSet<ca_related_company_contact_office_phone> ca_related_company_contact_office_phone { get; set; }
        DbSet<ca_related_company_partner_percent_owned> ca_related_company_partner_percent_owned { get; set; }
        DbSet<ca_related_person> ca_related_person { get; set; }
        DbSet<ca_related_person_contact> ca_related_person_contact { get; set; }
        DbSet<ca_related_person_contact_home_phone> ca_related_person_contact_home_phone { get; set; }
        DbSet<ca_related_person_contact_mobile> ca_related_person_contact_mobile { get; set; }
        DbSet<ca_related_person_contact_work_phone> ca_related_person_contact_work_phone { get; set; }
        DbSet<ca_rule_execution_log> ca_rule_execution_log { get; set; }
        DbSet<ca_trust_applicant> ca_trust_applicant { get; set; }
        DbSet<ca_veda_fchk_resp> ca_veda_fchk_resp { get; set; }
        DbSet<ca_veda_fchk_resp_bcaerror> ca_veda_fchk_resp_bcaerror { get; set; }
        DbSet<ca_veda_fchk_resp_bcamessage> ca_veda_fchk_resp_bcamessage { get; set; }
        DbSet<ca_veda_fchk_resp_bcaservice> ca_veda_fchk_resp_bcaservice { get; set; }
        DbSet<ca_veda_fchk_resp_bcaservice_data> ca_veda_fchk_resp_bcaservice_data { get; set; }
        DbSet<ca_veda_fchk_resp_bcaservices> ca_veda_fchk_resp_bcaservices { get; set; }
        DbSet<ca_veda_fchk_resp_error> ca_veda_fchk_resp_error { get; set; }
        DbSet<ca_veda_fchk_resp_fchk_report> ca_veda_fchk_resp_fchk_report { get; set; }
        DbSet<ca_veda_fchk_resp_fchk_report_fchk_result> ca_veda_fchk_resp_fchk_report_fchk_result { get; set; }
        DbSet<ca_veda_fchk_resp_fchk_result_details> ca_veda_fchk_resp_fchk_result_details { get; set; }
        DbSet<ca_veda_fchk_resp_fchk_result_details_addr> ca_veda_fchk_resp_fchk_result_details_addr { get; set; }
        DbSet<ca_veda_fchk_resp_fchk_result_details_employer_phone_details> ca_veda_fchk_resp_fchk_result_details_employer_phone_details { get; set; }
        DbSet<ca_veda_fchk_resp_fchk_result_details_employment> ca_veda_fchk_resp_fchk_result_details_employment { get; set; }
        DbSet<ca_veda_fchk_resp_fchk_result_details_guarantor_phone_details> ca_veda_fchk_resp_fchk_result_details_guarantor_phone_details { get; set; }
        DbSet<ca_veda_fchk_resp_fchk_result_details_phone_details> ca_veda_fchk_resp_fchk_result_details_phone_details { get; set; }
        DbSet<ca_veda_fchk_resp_fchk_result_details_referee_phone_details> ca_veda_fchk_resp_fchk_result_details_referee_phone_details { get; set; }
        DbSet<ca_veda_fchk_resp_fchk_result_details_second_phone_details> ca_veda_fchk_resp_fchk_result_details_second_phone_details { get; set; }
        DbSet<ca_veda_fchk_resp_fchk_result_summary> ca_veda_fchk_resp_fchk_result_summary { get; set; }
        DbSet<ca_veda_fchk_resp_general_message> ca_veda_fchk_resp_general_message { get; set; }
        DbSet<ca_veda_fchk_resp_vchk_report> ca_veda_fchk_resp_vchk_report { get; set; }
        DbSet<ca_veda_fchk_resp_vchk_report_drivers_licence_result> ca_veda_fchk_resp_vchk_report_drivers_licence_result { get; set; }
        DbSet<ca_veda_fchk_resp_vchk_report_elect_roll_result> ca_veda_fchk_resp_vchk_report_elect_roll_result { get; set; }
        DbSet<ca_veda_fchk_resp_vchk_report_elect_roll_result_addr_indicator> ca_veda_fchk_resp_vchk_report_elect_roll_result_addr_indicator { get; set; }
        DbSet<ca_veda_fchk_resp_vchk_report_elect_roll_result_indiv_name_indicator> ca_veda_fchk_resp_vchk_report_elect_roll_result_indiv_name_indicator { get; set; }
        DbSet<ca_veda_fchk_resp_vchk_report_phone_list_result> ca_veda_fchk_resp_vchk_report_phone_list_result { get; set; }
        DbSet<ca_veda_fchk_resp_vchk_report_phone_list_result_addr_indicator> ca_veda_fchk_resp_vchk_report_phone_list_result_addr_indicator { get; set; }
        DbSet<ca_veda_fchk_resp_verification_suite_summary> ca_veda_fchk_resp_verification_suite_summary { get; set; }
        DbSet<ca_veda_vsa_resp> ca_veda_vsa_resp { get; set; }
        DbSet<ca_veda_vsa_resp_data_block_characteristic> ca_veda_vsa_resp_data_block_characteristic { get; set; }
        DbSet<ca_veda_vsa_resp_enquiry_report_pub_rec_or_cons_credit_info> ca_veda_vsa_resp_enquiry_report_pub_rec_or_cons_credit_info { get; set; }
        DbSet<ca_veda_vsa_resp_product_data> ca_veda_vsa_resp_product_data { get; set; }
        DbSet<ca_veda_vsa_resp_product_data_enquiry_report> ca_veda_vsa_resp_product_data_enquiry_report { get; set; }
        DbSet<ca_veda_vsa_resp_product_data_score_data> ca_veda_vsa_resp_product_data_score_data { get; set; }
        DbSet<ca_veda_vsa_resp_product_data_summary_data> ca_veda_vsa_resp_product_data_summary_data { get; set; }
        DbSet<ca_veda_vsa_resp_pub_rec_or_cons_credit_info_pers_insolvency> ca_veda_vsa_resp_pub_rec_or_cons_credit_info_pers_insolvency { get; set; }
        DbSet<ca_veda_vsa_resp_score_data_score> ca_veda_vsa_resp_score_data_score { get; set; }
        DbSet<ca_veda_vsa_resp_summary_data_data_block> ca_veda_vsa_resp_summary_data_data_block { get; set; }
        DbSet<ch_event> ch_event { get; set; }
        DbSet<ch_event_product> ch_event_product { get; set; }
        DbSet<ch_process> ch_process { get; set; }
        DbSet<ch_submission> ch_submission { get; set; }
        DbSet<in_global_interface_log> in_global_interface_log { get; set; }

        DbSet<TEntity> GetDbSet<TEntity>() where TEntity : class;
    }
}
